# Generated by Django 5.1.2 on 2024-12-18 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0002_promotion"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Promotion",
        ),
    ]
