from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register_view, name="register"),
    path("query/places/<str:q>", views.query, name="query"),
    path("flight", views.flight, name="flight"),
    path("review", views.review, name="review"),
    path("flight/ticket/book", views.book, name="book"),
    path("flight/ticket/payment", views.payment, name="payment"),
    path('flight/ticket/api/<str:ref>', views.ticket_data, name="ticketdata"),
    path('flight/ticket/print',views.get_ticket, name="getticket"),
    path('flight/bookings', views.bookings, name="bookings"),
    path('flight/ticket/cancel', views.cancel_ticket, name="cancelticket"),
    path('flight/ticket/resume', views.resume_booking, name="resumebooking"),
    path('contact', views.contact, name="contact"),
    path('privacy-policy', views.privacy_policy, name="privacypolicy"),
    path('terms-and-conditions', views.terms_and_conditions, name="termsandconditions"),
    path('about-us', views.about_us, name="aboutus"),
    path('travel-info', views.travel_info, name="travelinfo"),
    path('travel-info/baggage-info', views.baggage_info, name="baggage_info"),
    path('travel-info/baggage-info/special-baggage', views.special_baggage, name="special_baggage"),
    path('travel-info/baggage-info/excess-baggage', views.excess_baggage, name="excess_baggage"),
    path('travel-info/baggage-info/carry-on-baggage', views.carry_on_baggage, name="carry_on_baggage"),
    path('travel-info/baggage-info/baggage-allowance', views.baggage_allowance, name="baggage_allowance"),
    path('travel-info/check-in', views.check_in, name="check_in"),
    path('travel-info/special-services', views.special_services, name="special_services"),
    path('travel-info/travel-documents', views.travel_documents, name="travel_documents"),
    path('travel-info/special-services/special-meals', views.special_meals, name="special_meals"),
    path('travel-info/special-services/travelling-with-kids', views.travelling_with_kids, name="travelling_with_kids"),
    path('travel-info/special-services/pregnant-passengers', views.pregnant_passengers, name="pregnant_passengers"),
    path('travel-info/special-services/disabled-passengers', views.disabled_passengers, name="disabled_passengers"),
    path('travel-info/travel-documents/entry-exit-regulations', views.entry_exit_regulations, name="entry_exit_regulations"),
    path('travel-info/travel-documents/health-status', views.health_status, name="health_status"),
    path('travel-info/travel-documents/identification-documents-visa', views.identification_documents_visa, name="identification_documents_visa"),
]